# Generated by Django 4.0.2 on 2022-02-28 12:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django_cryptography.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_title', models.CharField(max_length=200)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Votes',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField()),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2022, 2, 28, 12, 35, 46, 233076, tzinfo=utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repy_text', models.TextField()),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2022, 2, 28, 12, 35, 46, 234076, tzinfo=utc))),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='body.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reply',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', django_cryptography.fields.encrypt(models.CharField(max_length=200))),
                ('photo', django_cryptography.fields.encrypt(models.ImageField(blank=True, null=True, upload_to='photos'))),
                ('phone', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=200, null=True))),
                ('age', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=5, null=True))),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('rating', models.CharField(blank=True, max_length=200, null=True)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2022, 2, 28, 12, 35, 46, 232076, tzinfo=utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bodies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Person',
                'ordering': ['-id'],
            },
        ),
    ]
