# Generated by Django 4.0.2 on 2022-02-28 21:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Votes',
        ),
        migrations.AlterField(
            model_name='person',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 28, 21, 59, 20, 911475, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reply',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 28, 21, 59, 20, 919479, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='review',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 28, 21, 59, 20, 911475, tzinfo=utc)),
        ),
    ]
