# Generated by Django 4.0.2 on 2022-02-20 11:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0002_votes_alter_person_options_alter_review_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Reply'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Review'},
        ),
        migrations.RemoveField(
            model_name='person',
            name='created_at',
        ),
        migrations.AddField(
            model_name='person',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 20, 11, 20, 41, 77270, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='reply',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 20, 11, 20, 41, 79276, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='review',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 20, 11, 20, 41, 78270, tzinfo=utc)),
        ),
    ]
