# Generated by Django 4.0.2 on 2022-04-23 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0002_remove_review_total_likes_review_total_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='total_likes',
        ),
    ]
