# Generated by Django 4.0.2 on 2022-02-20 11:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_myuser_joined_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='joined_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 20, 11, 20, 41, 102268, tzinfo=utc)),
        ),
    ]
